### ISSUE TITLE
Re-consider exposing eth_getLogs

### ISSUE THREAD

**Issue by yarkinwho** [eosnetworkfoundation/eos-evm#310]
Currently eth_getLogs is not working in full https://github.com/eosnetworkfoundation/TrustEVM/issues/307

But we noticed that this call can be very costly even with the optimization from the silkworm.

Maybe we should consider keep blocking this API from public to defend against DoS

Special applications such as explorer or Oracles can use local silkworm nodes to access this API if we make local node options available.

**Comment by Joshua2Mars** [comment]
We will create a new issue to capture the work there. The performance limit of this kind of interface.
