### ISSUE TITLE
return descriptive errors when transaction validation fails in pushtx action

### ISSUE THREAD

**Issue by elmato** [eosnetworkfoundation/eos-evm#408]
assertion failure with message: validate_transaction error
vs.
insufficient funds for gas * price + value

**Comment by arhag** [comment]
If we go with the error code approach, then we need to create a Markdown document in docs folder to document the different error codes the contract may return. Provide a mapping between a particular range of EOS EVM Contract error codes to the various pre-validation and validation error cases that can be returned by the EVM (captured here: https://github.com/eosnetworkfoundation/silkworm/blob/b8470c70901a2896fe85fc537b375f7b87a15923/core/silkworm/consensus/validation.hpp).

**Comment by arhag** [comment]
We decided instead to just go with converting to descriptive messages in the contract and providing that as the abort error string. The error string should still include the enum error value in a systematic way.

**Comment by yarkinwho** [comment]
After another discussion, we decide to return string error desc directly.
