### ISSUE TITLE
Pull in some fixes to RPC from silkrpc upstream

### ISSUE THREAD

**Issue by arhag** [eosnetworkfoundation/eos-evm#413]
Only the low hanging fruit that do not require a lot of refactoring for now.

**Comment by juanm95** [comment]
I was told this might include support for Batched Request Objects, just added that here for visibility in case it doesn't.

**Comment by yarkinwho** [comment]
It's too dangerous to pull in fixes when unit tests broken, tests need to be fixed first: #554

**Comment by Joshua2Mars** [comment]
We need to pull the upstream of Silkworm to update it to the latest version

**Comment by arhag** [comment]
This will be completed as part of the repo changes @elmato is planning which will include bringing the latest version of silkworm as part of that work.

**Comment by Joshua2Mars** [comment]
Tracked by a new issue: https://github.com/eosnetworkfoundation/eos-evm/issues/574
