### ISSUE TITLE
Benchmark of swaps/second

### ISSUE THREAD

**Issue by iamphoumin852** [eosnetworkfoundation/eos-evm#437]
Redo a benchmarking of swaps/second, including the documentation of how we achieved the results, keeping in mind the methodologies used in the Dragonfly research original benchmarks

Also bench two ways, one with OC, the other not

**Comment by Joshua2Mars** [comment]
https://docs.google.com/spreadsheets/d/1124JJIS0_nY0sTFWhuiBY6ZGBnmpdqv0dMIzGW3xXOg/edit?usp=drivesdk

**Comment by Joshua2Mars** [comment]
What is missing here:

We need an ariticle to exlpain more details, similar to the "The AMM Test" article that compares out performance to others.

1. What is the testing environment?
2. How do we get these numbers?
3. What do these numbers in the spreadsheet mean?
4. Where are our real gaps compared to other chains?

It may be for answering questions on the BD side of things.

Source: The AMM Test: A No BS Look at L1 Performance
https://medium.com/dragonfly-research/the-amm-test-a-no-bs-look-at-l1-performance-4c8c2129d581

**Comment by heifner** [comment]
Note `nodeos` should be run with `--signature-cpu-billable-pct 0` because it currently is including the trx signature recovery time spent in the thread-pool before execution begins at the default 50%. This is just billed time and should not be included in your reported values. This is one reason why INIT is so large.

**Comment by Joshua2Mars** [comment]
I will review and confirm with Ted and Zack to see if we add other thing or not.

**Comment by Joshua2Mars** [comment]
The initial goal was to test based on the same methodology and to share the test data with the community in the form of a blog. Currently, any technical aspect of this task has been completed.

**Comment by Joshua2Mars** [comment]
https://github.com/eosnetworkfoundation/eos-evm/issues/618
