### ISSUE TITLE
Build the system will make the ./silkworm/third_party/gmplib dirty

### ISSUE THREAD

**Issue by yarkinwho** [eosnetworkfoundation/eos-evm#457]
To reproduce, simply checkout a clean copy, make a full build, then git will report dirty.

Though it seems not causing real trouble, it's annoying and may hide real problems.

We should investigate it when got time.

**Comment by arhag** [comment]
This has been resolved by the `main` branch of the new repo containing `eos-evm-node` and `eos-evm-rpc`: https://github.com/eosnetworkfoundation/eos-evm-node
