### ISSUE TITLE
Return a nice description page when GET api endpoint 

### ISSUE THREAD

**Issue by yarkinwho** [eosnetworkfoundation/eos-evm#460]
Currently we will return 500 as API endpoints are supposed to accept POST requests.

It would be nice to return something other than 500 to avoid confusion as 500 may cause people to think the API is down.

**Comment by yarkinwho** [comment]
Testnet done with #518

**Comment by kj4ezj** [comment]
(from video)

@yarkinwho will share specific examples of other Blockchain projects that return a `301` or other `300` request with a web page, then assign this issue back to me.

**Comment by yarkinwho** [comment]
Per discussion, the decision is return a page notify people this endpoint is not supposed to be accessed directly and give out a link to some landing page.
