### ISSUE TITLE
Show silkworm version (commit) when displaying eos-evm-node version

### ISSUE THREAD

**Issue by elmato** [eosnetworkfoundation/eos-evm#484]

**Comment by arhag** [comment]
We agreed that there is no reason to make a special case for the silkworm submodule versus all other submodules that could be misconfigured. Assuming a reliable build process is used to build the executables, it is sufficient to just have the git commit hash for the top-level repo (currently eos-evm) to identify the commit hashes of all submodules down the hierarchy.

So this issue will be closed as not planned.
