### ISSUE TITLE
Fix unit test framework for node and rpc

### ISSUE THREAD

**Issue by yarkinwho** [eosnetworkfoundation/eos-evm#554]
The old test framework from silkworm seems broken, we need fix that to better guard the code.

Depends on https://github.com/eosnetworkfoundation/eos-evm/issues/589.

**Comment by elmato** [comment]
Test are fixed (only one failing, empty tx serialization) after this commit
https://github.com/eosnetworkfoundation/silkworm/commit/efb5a2393c3f84dd7c7791c13ac93fd39f540802
