### ISSUE TITLE
Need an API for retrieving contract ABIs

### ISSUE THREAD

**Issue by cc32d9** [eosnetworkfoundation/eos-evm#556]
Currently there's no programmatic way to retrieve an ABI for a contract on EVM. 

On Ethereum, etherscan API is often used for that:  https://github.com/llamafolio/evm-indexer/blob/ddf6b8e0b99dd9f051ab48e1c07ab6cfc8a5eba3/bin/abi-fetcher.rs#L99

Telos EVM is utilizing https://sourcify.dev/
https://t.me/antelopedevs/325310

**Comment by yarkinwho** [comment]
It's already provided by the explorer. 
ABIs are available for verified contracts.
Please check https://explorer.testnet.evm.eosnetwork.com/api-docs
