### ISSUE TITLE
Estimate gas failed but execution goes through

### ISSUE THREAD

**Issue by yarkinwho** [eosnetworkfoundation/eos-evm#568]
Some partner is reporting contract calls that will revert during estimate gas but can go through if you send the request anyway. 

Contract at 0xA5540C40865300c7774F8b341B4A4aF060efAeaf on testnet.

They provided scripts and ABI for the contract. The script might need some modification to work.
[TestEVMRegister.ts.txt](https://github.com/eosnetworkfoundation/eos-evm/files/11632312/TestEVMRegister.ts.txt)
[EVMRegistrarController.json.txt](https://github.com/eosnetworkfoundation/eos-evm/files/11632314/EVMRegistrarController.json.txt)

**Comment by Joshua2Mars** [comment]
Need a urgent fix for this bugs, otherwise we need to delay release
