### ISSUE TITLE
Batched Requests compatibility

### ISSUE THREAD

**Issue by Joshua2Mars** [eosnetworkfoundation/eos-evm#569]
Batched Requests are not currently supported in JSON RPC

https://github.com/eosnetworkfoundation/docs/pull/123

**Comment by Joshua2Mars** [comment]
tracked by https://github.com/eosnetworkfoundation/eos-evm/issues/413

**Comment by arhag** [comment]
This has been resolved by the `main` branch of the new repo containing `eos-evm-node` and `eos-evm-rpc`: https://github.com/eosnetworkfoundation/eos-evm-node
