### ISSUE TITLE
Spike - Bridge need to provide Both Tx hash of EOS native and Tx hash of EVM

### ISSUE THREAD

**Issue by Joshua2Mars** [eosnetworkfoundation/eos-evm#575]

**Comment by yarkinwho** [comment]
https://hackmd.io/NFen6KGlTOSyDtgust8Cpg

**Comment by yarkinwho** [comment]
Updated with some sample js code.

**Comment by Joshua2Mars** [comment]
Next step: We will achieve the MVP of this feature through some frontend functionalities in the following 2 sprints.
