### ISSUE TITLE
Funnel EVM Health Checks into CloudWatch

### ISSUE THREAD

**Issue by kj4ezj** [eosnetworkfoundation/eos-evm#602]
As part of an epic for a unified metrics and alerting system around EVM infrastructure, this ticket is to get the status of infrastructure health checks flowing to CloudWatch. This is probably already happening "for free," but we need to get them into a single view and make this accessible to the EVM team. The interval of the health checks can be used as a starting point for the metric period.

## See Also
1. eos-evm [issue 602](https://github.com/eosnetworkfoundation/eos-evm/issues/602) - Funnel EVM Health Checks into CloudWatch
1. engineering [issue 48](https://github.com/eosnetworkfoundation/engineering/issues/48) - Collaborate with Operations on Unified Dashboarding Solution
1. engineering [issue 49](https://github.com/eosnetworkfoundation/engineering/issues/49) - Create Bot to Alert via IM on Specific Metrics
1. eos-evm [issue 603](https://github.com/eosnetworkfoundation/eos-evm/issues/603) - **SMS** Alerting for EVM Infrastructure Health Checks
1. engineering [issue 65](https://github.com/eosnetworkfoundation/engineering/issues/65) - **Email** Alerting for EVM Infrastructure Health Checks
1. telegram-bot [issue 1](https://github.com/eosnetworkfoundation/telegram-bot/issues/1) - Open-Source This Repo
1. engineering [issue 57](https://github.com/eosnetworkfoundation/engineering/issues/57) - Create Telegram Service Account
1. engineering [issue 58](https://github.com/eosnetworkfoundation/engineering/issues/58) - Create EVM **Testnet** Alert Channel Using Telegram Service Account
1. engineering [issue 64](https://github.com/eosnetworkfoundation/engineering/issues/64) - Create EVM **Mainnet** Alert Channel Using Telegram Service Account
1. engineering [issue 66](https://github.com/eosnetworkfoundation/engineering/issues/66) - Fix EVM CloudWatch Alerts

**Comment by wanderingbort** [comment]
This issue is considered completed
