### ISSUE TITLE
Silkworm changes to support advanced trustless bridge

### ISSUE THREAD

**Issue by arhag** [eosnetworkfoundation/eos-evm#609]
Make changes to silkworm to allow the EOS EVM Contract to retrieve the ordered list of message calls (with the call data) made to the reserved addresses. It is acceptable to create a hook to allow the contract to process all message calls made to any address (so that it can filter for only those it is interested in) assuming that does not negatively impact performance. If performance is an issue, silkworm can just filter it down to only the reserved addresses or even just a set of addresses specified by the contract. 

The way this enhancement is intended to be used is for the EOS EVM Contract to listen to all messages sent to the reserved address corresponding to the `eosio.evm` account name in the order in which they were dispatched to then do further processing on it. As part of this issue, unit tests are needed in EOS EVM Contract demonstrating this capability.

**Comment by Joshua2Mars** [comment]
A unit test needed in the next sprint
