### ISSUE TITLE
Initial iteration of eosio.erc2o contract

### ISSUE THREAD

**Issue by arhag** [eosnetworkfoundation/eos-evm#611]
Depends on #608.

Initial iteration should just use the `call` mechanism to automatically deploy and link an ERC-20 EVM contract for a new eosio.token-compatible token. This should not yet support upgradeability of the deployed contract. To add support for a new eosio.token-compatible token, an action requiring `get_self()` authorization must be called. This action will be the one to deploy and link the ERC-20 contract.

The initial version should also listen to `*:transfer` notification to make the `call` action to the linked ERC-20 EVM contract to make the tokens available within the EVM environment. However, it should not yet support moving tokens from EVM environment to the EOS environment.

Tests should demonstrate moving a USDT token from the EOS environment to the EVM environment. Tests should also show moving the ERC-20 version of the USDT tokens around between EVM accounts within the EVM environment.

**Comment by yarkinwho** [comment]
https://github.com/eosnetworkfoundation/evm-bridge-contracts/pull/2
