### ISSUE TITLE
Update the eos-evm repo to generate a binary archive of the wasm and abi files built for the eos-evm contract

### ISSUE THREAD

**Issue by stephenpdeos** [eosnetworkfoundation/eos-evm#632]
Can follow the leap-dev package model for how github actions can generate the archive. No need for debian package.

**Comment by oschwaldp-oci** [comment]
@stephenpdeos and @arhag - Is it enough that the `contract.yaml` workflow is creating a tarball of the build directory and uploading it?  See: https://github.com/eosnetworkfoundation/eos-evm/blob/main/.github/workflows/contract.yml#L64C1-L74C35

This was enough to get the `eos-evm-node` build and integration test running.

The creation of the tarball is here in the script: https://github.com/eosnetworkfoundation/eos-evm/blob/main/.github/workflows/build-contract.sh#L23

Could optimize the upload size a bit by excluding the object files like we've done here: https://github.com/eosnetworkfoundation/eos-evm-node/blob/gh-11-integration-test/.github/workflows/build-node.sh#L24
`ee 'tar -czf build.tar.gz --exclude="*.o" build/*'`

**Comment by arhag** [comment]
@oschwaldp-oci: Yes, that seems like a reasonable approach.
