### ISSUE TITLE
Create a tool that reads from a snapshot file and dumps the EVM contract state

### ISSUE THREAD

**Issue by elmato** [eosnetworkfoundation/eos-evm#636]
This tool will receive a regular EOS snaphot file and will output:
 - json file json file containing all the data used to calculate the EVM state root.
 - json file with all the auxiliary EVM contact tables used by the contract

**Comment by elmato** [comment]
Link to the branch that has the tool under `programs/evm-state-dump`
https://github.com/elmato/leap/tree/evm-state-dump

**Comment by stephenpdeos** [comment]
No PR associated since this is a temporary solution, see above associated branch, which won't be integrated anywhere yet officially at this time.
