### ISSUE TITLE
Reset evm-mainnet AWS IAM User Account

### ISSUE THREAD

**Issue by Joshua2Mars** [eosnetworkfoundation/eos-evm#638]
I lost one of my phones with 2FA, please re-create an AWS account and delete the old one for EVM mainnet and testnet environment. Thanks!

**Comment by kj4ezj** [comment]
The customer's account has been reset. First-login credentials were shared in an encrypted email, and the decryption key to the email was shared via IM.

**Comment by kj4ezj** [comment]
I have verified the customer logged into the `evm-mainnet` AWS IAM user account three days ago, changed his password, and setup multi-factor authentication (MFA).

The request for an `evm-testnet` IAM user is captured and tracked in eos-evm [issue 640](https://github.com/eosnetworkfoundation/eos-evm/issues/640).
